import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarWrapper from "./navbar-wrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Adawardrobe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="header">
          <div className="header-content">
            <h1 className="header-title">Anciens meubles, nouvelle vie</h1>
          </div>
          <p className="header-subtitle">
            Donnez une seconde chance à vos meubles ♻️
          </p>
        </header>
        <NavbarWrapper />
        <main>{children}</main>
        <footer>© {new Date().getFullYear()} - Meubles Recyclés</footer>
      </body>
    </html>
  );
}
